exec { '/usr/bin/env apt-get -y update': }
-> exec { '/usr/bin/env apt-get -y install nginx': }
-> exec { '/usr/bin/env sed -i "/listen \[::\]:80 default_server/ a\\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default': }
-> exec { '/usr/bin/env sed -i "/listen \[::\]:80 default_server/ a\\add_header X-Served-By \"$HOSTNAME\";" /etc/nginx/sites-available/default': }
-> exec { '/usr/bin/env sed -i "/redirect_me/ a\\error_page 404 /custom_404.html;" /etc/nginx/sites-available/default': }
-> exec { '/usr/bin/env # echo "Ceci n\'est pas une page" > /var/www/html/custom_404.html': }
-> exec { '/usr/bin/env mkdir -p /data/web_static/releases/test/': }
-> exec { '/usr/bin/env mkdir -p /data/web_static/shared/': }
-> exec { '/usr/bin/env echo "simple content, to test your Nginx configuration" > /data/web_static/releases/test/index.html': }
-> exec { '/usr/bin/env ln -sf /data/web_static/releases/test/ /data/web_static/current': }
-> exec { '/usr/bin/env sed -i "/^\tlocation \/ {$/ i\\location /hbnb_static {\n\talias /data/web_static/current/;\n\tautoindex off;\n}" /etc/nginx/sites-available/default': }
-> exec { '/usr/bin/env systemctl restart nginx': }
-> exec { '/usr/bin/env chown -R ubuntu:ubuntu /data/': }
